# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blogs"
  pageRef = "en/posts"
  weight = 10

[[main]]
  name = "Thoughts"
  pageRef = "en/thoughts"
  weight = 15


[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Entertainments"
  parent = "Categories"
  pageRef = "entertainments"
  weight = 10

[[main]]
  name = "Tools"
  parent = "Categories"
  pageRef = "tools"
  weight = 20

[[subnavigation]]
  name = "Roam（to do）🚧"
  pre = "wand-magic-sparkles"
  pageRef = "tags"
  weight = 10

[[subnavigation]]
  name = "Subscribe（to do）🚧"
  pre = "rss-square"
  pageRef = "categories/awesome"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30


[[main]]
  name = "About me"
  pageRef = "about"
  weight = 50



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

[[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20
